version: '3'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - rate-limiter-network
  rate-limiter:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    volumes:
      - .:/app
    networks:
      - rate-limiter-network

networks:
  rate-limiter-network:
    driver: bridge